### ISSUE TITLE
Update for Helia 2.1

### ISSUE THREAD

**Issue by Jollarvia** [ipfs/helia-remote-pinning#41]
This one is simple. Please update for Helia 2.1 when you get a chance. The current version works only with Helia 1.3.11.
merging https://github.com/ipfs/helia-remote-pinning/pull/39/commits/a3e3c785f1f07ab955834df5ba50cdf50b63fd3c might do the trick.

**Comment by SgtPooki** [comment]
The latest helia is now in use, releasing shortly.
